### ISSUE TITLE
Motor did not lock and unlock correctly because of wrong variable?

### ISSUE THREAD

**Issue by astyrmoe** [ttm4115-group11/bike-rack#10]
Hi! Did we use the wrong variable here, @haavarop? :)
Should it be a duration variable and not a pin variable?

https://github.com/ttm4115-group11/bike-rack/blob/2da99972da352dc6b88828394f7cf4d7ccae2046/LED.py#L58

**Comment by astyrmoe** [comment]
We should probably also change the file name to GPIO.py and not name it LED-py. Should be more correct

**Comment by haavarop** [comment]
LOCK_PIN is the wrong yes. It should be `LOCK_DURATION`
The file should also be renamed yes.
